sudo: true
dist: trusty
language: generic

addons:
  apt:
    packages:
    - snapd

install:
  - sudo snap install hugo
  - export PATH=/snap/bin:$PATH

script:
  - hugo --enableGitInfo

deploy:
    type: git
    repo: git@github.com:javashifeng/javashifeng.github.io.git  #这里的网址填你自己的
    branch: master